#!/usr/bin/env bash

############################################################################## 
# This is a very slight modification of Drew Hunter's (@ddh__)
# gist https://gist.github.com/drewhunter/8037753
############################################################################## 

# Exit on error
set -eu
 
declare -a FILE_PATTERNS=('app/code/core' 'app/Mage.php$' '^index.php$')
 
EXIT_STATUS=0
while read FILE; do
  for FILE_PATTERN in ${FILE_PATTERNS[@]}; do
    if [[ $FILE =~ $FILE_PATTERN ]]; then
        echo "Core change detected: $FILE" >&2
        EXIT_STATUS=1
    fi
  done
done < <(git diff-index --cached --name-only HEAD)
 
exit $EXIT_STATUS;
